/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button/Button.vue')['default']
    CameraModal: typeof import('./components/Camera/cameraModal.vue')['default']
    IconHeroiconsOutlineHome: typeof import('~icons/heroicons-outline/home')['default']
    IconLucideHome: typeof import('~icons/lucide/home')['default']
    IconLucideMoon: typeof import('~icons/lucide/moon')['default']
    IconLucideSun: typeof import('~icons/lucide/sun')['default']
    IconLucideUserCircle: typeof import('~icons/lucide/user-circle')['default']
    Input: typeof import('./components/Input/Input.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    ModeSwitcher: typeof import('./components/ModeSwitcher.vue')['default']
    NavBar: typeof import('./components/NavBar/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/Select/Select.vue')['default']
    SideManuBar: typeof import('./components/SideMenuBar/SideManuBar.vue')['default']
    UserOptions: typeof import('./components/UserOptions.vue')['default']
  }
}
